### ISSUE TITLE
Accessibility verification on Authenticated Pages by HTML_Codesniffer

### ISSUE THREAD

**Issue by reach2akram** [squizlabs/HTML_CodeSniffer#108]
I have to use HTML_Codesniffer for one of my client for Accessibility Testing hence I am just figuring/searching out the features of it. When I tried it on an authenticated page (My Gmail inbox) I was able to use it but when I tried it on facebook (after login into the facebook account) it is not working. And I am wonder that, it is even not working on the 'home page - Login page of Facebook'.

I have to suggest this tool for Accessibility testing but I am little worried about that will it work on Authenticated Pages or not. It will be a Learning Application ( But my bad is that I don't have the web app in my hand right now so that I can check it) on which I will have to test accessibility.

Please help me out and if there is any documentation you can provide that will be really appreciable.

Thanks
-Akram

**Comment by pgindia** [comment]
Hi, Thanks for the reply. This really helps!!

How does this tools works with authenticated pages , if i automate the whole process using Jenkins.

**Comment by gsherwood** [comment]
> How does this tools works with authenticated pages , if i automate the whole process using Jenkins.

The tool doesn't do any authentication for you. You'll need to authenticate first and then run the tool over the HTML that you get back.

This tool is designed to be run manually from within the browser. But being JS, you can also run it server-side. But you'll need to handle the authentication yourself in those cases.

**Comment by lwright-sq** [comment]
Closing.

I suspect it may have had more to do with things related to HTTPS than authentication, but it may not have been. However, the current version of the HTMLCS bookmarklet does support loading via HTTPS, although whether this is effective may depend on a site's CORS policy.
