### ISSUE TITLE
Need to Run HTML_CodeSniffer on Local Intranet

### ISSUE THREAD

**Issue by reach2akram** [squizlabs/HTML_CodeSniffer#112]
I downloaded 'HTML_CodeSniffer-master.zip' on my local machine. My application (that need to be tested for accessibility) is hosted in my Local Intranet Server. Could you please guide (or provide steps) me that how can I use it for Accessibility Testing ?

**Comment by gsherwood** [comment]
You should probably just use the pre-built bookmarklet to do this. You can install the bookmarklet here: http://squizlabs.github.io/HTML_CodeSniffer/

**Comment by reach2akram** [comment]
Hey, that's fine. I already installed the bookmarklet and used to test the application that is hosted outside my local intranet (I mean Internet).

But now the situation is that my application is hosted on intranet (mean with in my office), so how can I test it using HTML_CodeSniffer.

Hope you understand !

**Comment by gsherwood** [comment]
The bookmarklet has no server-side component, so it runs entirely in your browser. As long as you can view a page, the bookmarklet can access the content and check the accessibility of it.
