### ISSUE TITLE
Should not warn when `label`'s `for` attribute points to `button` control

### ISSUE THREAD

**Issue by zacechola** [squizlabs/HTML_CodeSniffer#117]
The following warning appears when a `label` element's `for` attribute references the id of `button`.

>This label's "for" attribute contains an ID for an element that is not a form control. Ensure that you have entered the correct ID for the intended element.

[The `button` element is labelable](http://www.w3.org/TR/html5/forms.html#category-label). 

[This jsbin shows the issue](http://jsbin.com/fexole/1).

**Comment by lwright-sq** [comment]
Hi Zac,

Thanks for the report. I wouldn't say that label elements do much for a button for WCAG2 purposes (when the button text itself is supposed to be the accessible title), but that message saying "it's not a form control" and thus an error/warning for putting a label element to it doesn't seem right to me.

Marking as a bug and I should have a resolution reasonably soon. Thanks again.

**Comment by zacechola** [comment]
Agreed. Thanks for looking at it.

**Comment by lwright-sq** [comment]
Auditor 2.0.5 (uploaded this morning) should not cause this issue.
