### ISSUE TITLE
Cannot view detailed bookmarklet report on pages using a Frameset

### ISSUE THREAD

**Issue by jssh** [squizlabs/HTML_CodeSniffer#118]
On some pages I can run the bookmarklet and it will show the pop up box with errors, warnings, notices. But when I click on "view report", nothing happens. Is there a way around this or is it a issue with the web application? https://home.cunyfirst.cuny.edu/psp/cnyepprd/GUEST/HRMS/c/HRS_HRAM.HRS_CE.GBL

**Comment by lwright-sq** [comment]
Hi jssh,

Thanks for the report. I'm definitely marking this as a bug in the Auditor - it looks specific to pages/apps within framesets.

What's going on is that the standards and sniffs get placed in the top window element (the frameset's window in this case) but the auditor gets placed in the largest frame (from what I remember). There's some mismatch between where the auditor things the standards are located and where they actually are.

Thanks again; should be able to get you a resolution and an updated auditor soon.

**Comment by lwright-sq** [comment]
Auditor 2.0.5 (uploaded this morning) now should not cause this issue.
