### ISSUE TITLE
What is the automation coverage of 'HTML Code Sniffer' tool?

### ISSUE THREAD

**Issue by tapanabes** [squizlabs/HTML_CodeSniffer#125]
I am using 'HTML Code Sniffer' tool to test my web application Accessibility. When I run 'HTML Code Sniffer' on web page the automation coverage is found very less. I need to make a report for automation coverage. 

I am not able to found the accessibility coverage through ‘HTML Code Sniffer’ for below success criteria, while related content is available on my website:

A.	1.2.1 (Audio and Video only prerecorded)
   a.	Prerecorded audio only: An alternative for time-based media is provided that presents   equivalent information for prerecorded audio-only content.
   b.	Prerecorded vide only: Either an alternative for time based media or an audio track is provided that presents equivalent information for prerecorded video-only content.
B.	1.2.2 Captions(Prerecorded) : Captions are provided for all prerecorded audio content in synchronized media.
C.	1.2.3 Audio Description or Media Alternative (PreRecorded) – Audio Description of the prerecorded video content is provided for synchronized media.
D.	1.2.5 Audio Description (Prerecorded) : Audio Description is provided for all prerecorded video content. 
E.	1.3.3 (Sensory Characteristics) : Instruction provided for understanding and operating content do not rely on sensory characteristics of component such as shape, size, visual location.
F.	1.4.1 (Use of Color) : Color is not used as the only visual means of conveying information.
G.	1.4.4 (Resize Text) : Text can be resized without assistive technology up to 200 percent without loss of content or functionality.
H.	1.4.5 (Images of Text) : Text is used to convey information rather than images of text.
I.	2.4.3 (Focus Order): If a web page can be navigate sequentially and the navigation sequence affect meaning, focusable component receive focus in an order that preserve meaning and operability.
J.	2.4.6 (Heading and Label) : Heading and Label describe topic or purpose.
K.	3.2.1 (On Focus) : When any component receive focus, it does not initiate a change of context. 
L.	3.3.1 (Error Identification): If an input error is automatically detected, the item that is in error is identified and the error is described to the user in text. 
M.	  3.3.3 (Error Suggestion) : If an input error is automatically detected and suggestions for correction are known, then the suggestion are provided to the user.
N.	And many more……

Above mentioned success criteria related content are available on my application. Accessibility defect can be found through manual testing but ‘HTML Code Sniffer’ tool is not able to find issues related to above mentioned success criteria.

Could you please explain how we can test these types of success criteria using ‘HTML Code Sniffer’ tool.

If HTML Code Sniffer is not able to capture these success criteria related issues then could you please share what is the Success Criteria coverage of this tool? 

It will be great help for me to generate the report for automation coverage using ‘HTML Code Sniffer’. 

-Thanks,
Tapan Garg

**Comment by reach2akram** [comment]
I am facing the same issue. 

Please suggest. Thanks in advance

**Comment by gsherwood** [comment]
These docs are probably what you need: http://squizlabs.github.io/HTML_CodeSniffer/Standards/WCAG2/

**Comment by tapanabes** [comment]
Thanks for your comment. I will go through this document. Its a great help and get back to you on this in case if face any problem.
