### ISSUE TITLE
How I can check below success criteria using 'HTML code sniffer' tool

### ISSUE THREAD

**Issue by tapanabes** [squizlabs/HTML_CodeSniffer#129]
I am using 'HTML Code Sniffer' tool to test my web application Accessibility. I just want to know if I can check below success criteria through ‘HTML Code Sniffer’:

A. 1.2.2 Captions(Prerecorded)
B. 1.2.3 Audio Description or Media Alternative (PreRecorded)
C. 1.2.4 Captions (Live)
D. 1.2.5 Audio Description (Prerecorded)
E. 1.3.3 (Sensory Characteristics)
F. 1.4.1 (Use of Color)
G. 1.4.2 (Audio Control)
H. 1.4.5 (Images of Text)
I. 2.4.3 (Focus Order)
J. 2.4.5 (Multiple Ways)
K. 2.4.7 (Focus Visible)
L. 3.1.2 (Language of parts)
M. 3.2.1 (On Focus)
N. 3.2.3 (Consistent Navigation)
O. 3.2.4 (Consistent Identification)
P. 3.3.1 (Error Identification)
Q. 3.3.3 (Error Suggestion)
R. 3.3.4 (Error Prevention [Legal, Financial Data])

Could you please suggest how we can test these types of success criteria using ‘HTML Code Sniffer’ tool.
If HTML Code Sniffer is not able to capture these success criteria related issues then could you please share what is the Success Criteria coverage of this tool?

It will be great help for me to generate the report for automation coverage using ‘HTML Code Sniffer’.

-Thanks,
Tapan Garg

**Comment by gsherwood** [comment]
These docs are probably what you need: http://squizlabs.github.io/HTML_CodeSniffer/Standards/WCAG2/

**Comment by tapanabes** [comment]
Thanks for your comment. I will go through this document. Its a great help and get back to you on this in case if face any problem.
