### ISSUE TITLE
Merging / Collaborating etc.

### ISSUE THREAD

**Issue by yargalot** [squizlabs/HTML_CodeSniffer#131]
Hey Guys, 

Been wondering, I'm finding myself with less time these days to maintain the repo's below. Was wondering if you guys would be interested in helping maintain them / work on them. They get a few downloads on NPM each month. Access sniff is a node module using htmlcs for the grunt/gulp build tasks.

https://github.com/yargalot/AccessSniff
https://github.com/yargalot/grunt-accessibility
https://github.com/yargalot/gulp-accessibility

Thought I would open up the possibility here, I can see a few issues on board here about report generation which the modules solve.

**Comment by lwright-sq** [comment]
Hi Steven,

Thanks for the offer.

We'll take a look at them for inclusion into the contrib folder and/or improvement of the scripts we have now. I think I already put an earlier version of your Grunt script into Contrib/ so it might be worth either updating it there, or changing it to work as a Git submodule (perhaps aside the Gulp script).

(For reference as I must admit I hadn't heard of Grunt or Gulp until Steven brought it up: [Grunt](https://grunt.herokuapp.com/), [Gulp](http://gulpjs.com).)

No guarantees about when I/we at Squiz Labs can get around to it at this stage as our resources are pretty flat-out at this stage, but will certainly keep this proposal open.

~ Luke
