### ISSUE TITLE
Button with no type attribute

### ISSUE THREAD

**Issue by GaryJones** [squizlabs/HTML_CodeSniffer#136]
> Form does not contain a submit button (input type="submit", input type="image", or button type="submit").

The default value for `button` `type` attribute, if omitted, is `submit`, so `<button>` should not trigger this error.

**Comment by lwright-sq** [comment]
Hi Gary,

Sorry I haven't been able to reply to you in a timely manner - been extremely busy lately.

Thanks for pointing this out to me - makes sense; I probably thought that for some reason the default type was just "button", but you're right, it's not.

I can't guarantee a certain timeframe for this, but it's something I will try to get in reasonably soon. Thanks for the report!
