### ISSUE TITLE
HTMLCS.js link broken

### ISSUE THREAD

**Issue by mattoz0** [squizlabs/HTML_CodeSniffer#138]
Hey guys, cool project.
Just letting you know that your HTMLCS.js link is broken for the bookmarklet and also the widget on your website is broken because of the missing dependency.

![image](https://cloud.githubusercontent.com/assets/11494975/11109461/61ba87a0-893c-11e5-87f8-9676aaf4ab95.png)

**Comment by gsherwood** [comment]
Thanks. We're fixing it now. Looks like a bad commit caused it a couple of hours ago during a new release.

**Comment by mattoz0** [comment]
I can confirm this is now resolved. Thanks!
