### ISSUE TITLE
Bookmarklet is injecting errors on to pages from GA

### ISSUE THREAD

**Issue by dak** [squizlabs/HTML_CodeSniffer#146]
Every time the Bookmarklet is opened or toggled between tests, it appears to be injecting Google Analytics code that is causing an error to be reported on subsequent executions.

Opening the Bookmarklet, closing it, and then reopening it appears to cause the error count to increase by 1, while toggling between AA and AAA causes it to increase by 3.

Below is the infringing injected element:
```
<img src="http://www.google-analytics.com/__utm.gif?utmwv=0.0&amp;utmn=1611378140&amp;utmhn=localhost&amp;utmp=/&amp;utmac=UA-359178-17&amp;utme=8%28Standard*Errors*Warnings*Notices%299%28WCAG2AA*0*0*1%29&amp;utmcc=__utma%3D111872281.586051357.1453341586.1453342637.1453342703.17%3B&amp;" style="display: none;">
```

**Comment by lwright-sq** [comment]
This has been fixed in the bookmarklet version. Thanks for the report.
