### ISSUE TITLE
ARIA role="presentation" not supported

### ISSUE THREAD

**Issue by Hywan** [squizlabs/HTML_CodeSniffer#149]
Hello :-),

[The `role="presentation"` definition](http://www.w3.org/TR/wai-aria/roles#childrenArePresentational) is the following:
> The DOM descendants are presentational. User agents SHOULD NOT expose descendants of this element through the platform accessibility API. If user agents do not hide the descendant nodes, some information may be read twice.

[A more detailed explanation](http://www.w3.org/TR/wai-aria/roles#presentation) can be found.

So, for instance, we can write this:
```xml
<a href="…" role="presentation">…</a>
```
and it is a valid HTML from the accessibility point of view.

What is the strategy to implement this in HTML_CodeSniffer? The goal is to check that any selected element in no a child or an element with a `role="presentation"` attribute.

**Comment by Hywan** [comment]
[The rule F92 from WCAG 2.0](http://www.w3.org/TR/WCAG20-TECHS/F92.html) can be worth to notice.

**Comment by ironikart** [comment]
Resolved in master branch by filtering presentation elements out of the main loop of elements to sniff and individually testing these elements for F92.
