### ISSUE TITLE
menu panel text is clipped on RTL pages

### ISSUE THREAD

**Issue by WW3** [squizlabs/HTML_CodeSniffer#152]
![image](https://cloud.githubusercontent.com/assets/468739/12516716/990f7796-c137-11e5-9a68-17e29eae50d6.png)

**Comment by ironikart** [comment]
Fixed this by setting text direction for the HTMLCS wrapper element. This won't fix all the issues encountered in the screenshot as there appears to be a fair bit of conflicting CSS which style elements by tag name which is automatically inherited. Other than overriding each individual element there isn't much we can do about those conflicts.
