### ISSUE TITLE
Incorrectly suggests adding summary attribute to HTML5 document

### ISSUE THREAD

**Issue by robfentress** [squizlabs/HTML_CodeSniffer#161]
When I have a table in an HTML5 document, HTML_CodeSniffer gives the following suggestion:

> If this table is a data table, consider using the summary attribute of the table element to give an overview of this table.

Since HTML5 does not include the `summary` attribute anymore, I believe this is incorrect advice.

**Comment by lwright-sq** [comment]
Hi Rob,

At the moment HTMLCS doesn't distinguish between HTML4 and HTML5 at the moment, things like this are shown as non-error messages for the time being.

Seeing HTML5 is a LOT more of a thing now, and now that the limitations to detection are winding down (eg. IE8 is basically dead), I'll be looking to implement a document type detection/setting feature (see #137 for instance) with a bit more priority. Watch this space.

**Comment by lwright-sq** [comment]
Hi Rob,

This change is now in the trunk, and should be in a released version soon I hope.

Thanks again for your report.

**Comment by Rudloff** [comment]
Hello,
In this in the current release? It still complains about the summary attribute in my HTML5 pages.
