### ISSUE TITLE
CodeSniffer error fails to run via command line from bash script

### ISSUE THREAD

**Issue by JordanGS** [squizlabs/HTML_CodeSniffer#164]
In an .sh file i have the following: `pa11y --config $FILENAME.js "$URL" > OUTPUT/$FILENAME.txt` with passed in parameters will randomly generate the following error:

```
 > Error: Test function errored for "https://mysite.ca/contact.html"
Error: HTML CodeSniffer: undefined is not an object (evaluating 'f.nodeType')
    at Object.<anonymous> (/home/automaton/.linuxbrew/lib/node_modules/pa11y/lib/pa11y.js:63:16)
    at Object.f [as onCallback] (/home/automaton/.linuxbrew/lib/node_modules/pa11y/node_modules/once/once.js:17:25)
    at /home/automaton/.linuxbrew/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:619:30
    at Array.forEach (native)
    at IncomingMessage.<anonymous> (/home/automaton/.linuxbrew/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:600:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any clarifications on this error would be appreciated, i am unsure myself after having attempted to troubleshoot on google and stack.

**Update:**
This doesn't always happen. Seems random, it'll work once or twice, then fail and go back and forth that way, etc.

**Update 2:** Running with debug flag

Welcome to Pa11y
```

 > PhantomJS browser created
 > Debug: PhantomJS page created
 > Debug: Opening "https://mysite.ca/contact.html" in PhantomJS
 > Debug: Opened "https://mysite.ca/contact.html" in PhantomJS
 > Testing the page "https://mysite.ca/contact.html"
 > Debug: Running beforeScript
 > Debug: Injecting HTML CodeSniffer
 > Debug: Injecting Pa11y
 > Debug: Running Pa11y on the page
 > Debug: PhantomJS page closed
 > Debug: PhantomJS browser exited
```

There is nothing else to the Pa11y report

I opened the ticket with Pa11y and they told me to open a ticket with code sniffer to see if this bug looked familiar to anyone. Any help would be appreciated. Cheers.

**Comment by ironikart** [comment]
Do you have an example URL where this error occurs? The issue may be related to the content that is being analysed, particularly if that content is being manipulated by javascript at runtime. It may explain the random nature of the issue as code sniffer may be run before/after or during other javascript manipulations.

**Comment by JordanGS** [comment]
@ironikart no sorry, i'm not sure anymore. It's been a really long time and i don't remember if i resolved this issue or not or what url i was testing, I moved onto to something else, creating a functional test to navigate pages and then evaluate with pally. If i get this issue again in the future, i'll open another issue.

**Comment by ironikart** [comment]
No worries. I wasn't able to replicate it with a small suite of pages via the phantomjs runner in this project so I'll close it off for now.
