### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by DanielaValero** [squizlabs/HTML_CodeSniffer#171]
Hello guys,

Is it between your plans to publish the package in npm?

At the moment is not available there: https://www.npmjs.com/browse/keyword/HTML_CodeSniffer

Therefore when using other packages that depend on this on CI environments, the packages won't be able to be installed every time, as a common scenario is that CI environments can't install npm dependencies from github.

Thanks in advance for your answer.

**Comment by ironikart** [comment]
It's something we're planning to do in the not-too-distant future. There are a few pull requests and issues we'd like to sort out first as well as porting over our build process.

**Comment by yargalot** [comment]
any updates on this @ironikart?

**Comment by ironikart** [comment]
@yargalot it's something we are still interested in doing.

We have a release on the horizon first before we think about committing to publishing to npm. The release itself basically ready to go and the changes work fine in isolation, but we have several products that use this that need to be tested thoroughly first.

**Comment by ecerta** [comment]
Not to be that guy, but any updates @ironikart ?

**Comment by ironikart** [comment]
@ecerta No progress to report yet, and no ETA.

**Comment by AntoniBertel** [comment]
Hi guys,

Could you please release?
It's really important for all organisations are mirroring public repositories for security reasons. They just can't pull the project from github. 
Thank you.

**Comment by ironikart** [comment]
HTMLCS has now been published to NPM:
https://www.npmjs.com/package/html_codesniffer
