### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by kahunacohen** [squizlabs/HTML_CodeSniffer#173]
Hi nice project. Especially like the bookmarklet. I do notice however that the project seems a bit abandoned. There are several pull requests that have been sitting around for a while and the CLI has several major bugs.

Our organization has been using a home-grown general HTML quality checker for years now, but we are investigating HTML_CodeSniffer as a replacement. I am curious if you are interested in having a potential maintainer (me) who would delve into the code, review pull requests etc. Seems that building off what you already have would be better than trying to roll our own from scratch. Thanks!

**Comment by gsherwood** [comment]
The project is absolutely not abandoned. But it is typically worked on in bursts.

Thanks for your offer of maintenance, but it is not required at this stage. This project is backed by a company with a team of developers, so we've got plenty of people with access to work on it.

**Comment by dylanb** [comment]
@kahunacohen we are always looking for contributors to the https://github.com/dequelabs/axe-core project and related projects. While we have an extension, we do not have a bookmarklet and that seems like a nice way for you to contribute.

**Comment by kahunacohen** [comment]
There is a bookmarklet isn't there? It's very nice. I am confused. However the CLI is broken in master with several fix suggestions in pull requests. Eg. https://github.com/squizlabs/HTML_CodeSniffer/pull/170. I am not complaining...just saying that to me the project looks like it could use some attention.

**Comment by gsherwood** [comment]
> I am not complaining...just saying that to me the project looks like it could use some attention.

Noted. I'll poke people to get a few things looked into as soon as time permits.
