### ISSUE TITLE
Unable to build using grunt

### ISSUE THREAD

**Issue by leny** [squizlabs/HTML_CodeSniffer#177]
Hi, 

I was trying to use the `grunt build` command when got this error : 

    >> Error: Unable to read "Contrib/Build/umd-header.js" file (Error code: ENOENT)

The file is apparently missing in the source tree.

Thanks in advance,

**Comment by leny** [comment]
Add cross reference : #166

Apparently, the two files `umd-header.js` & `umd-footer.js` are mentionned but not included in the    f79cf0a2584f0a69760e0d5518bab77593084275 commit.

**Comment by ironikart** [comment]
Looks like an issue with the .gitignore patterns for the `build/` directory. I've force added it for now to get it building again but may review the ignored file patterns in future.

**Comment by leny** [comment]
Thanks!
