### ISSUE TITLE
Getting different results from Bookmarklet and pasting the source code in the HTML_Sniffer

### ISSUE THREAD

**Issue by jtriolo61** [squizlabs/HTML_CodeSniffer#181]
Hi, 

We need an answer to make sure that we are compliant using the HTML_CodeSniffer.  We used the HTML_CodeSniffer by pasting in the page source.  After going thru each page in our web application, the errors for both WCAG 2.0 AAA and Section 508 were down to 0.

But then we used the Accessibility Auditor Bookmarklet and then we got quite a few errors.  What is the proper approach to making sure we are compliant?

I have attached a word document detailing the issue we are having. 

Thanks, 

Jenna Triolo
eSchoolData

**Comment by ironikart** [comment]
Hi, I'm removing that word document because of the possibility of viruses. Please post your list of issues in a text comment instead.

**Comment by jtriolo61** [comment]
![image](https://cloud.githubusercontent.com/assets/23505223/20364227/47fa4b32-ac10-11e6-8ba6-649c3dc15df3.png)

This is the page we are sniffing. 

![image](https://cloud.githubusercontent.com/assets/23505223/20364241/616a37b2-ac10-11e6-9263-0f1c68b2505c.png)

Pasted the page source code: 

![image](https://cloud.githubusercontent.com/assets/23505223/20364275/7afaa004-ac10-11e6-8913-8e73c1dc252d.png)

No errors for WCAG 2.0 AAA and Section 508: 

![image](https://cloud.githubusercontent.com/assets/23505223/20364338/bdbc1efe-ac10-11e6-9680-d65061a0fe63.png)

However when we use the widget, we get 12 errors for WCAG 2.0 AAA.  

Do we need to use the widget to be in compliance or will using the page source pasted into the sniffer be OK to meet compliance.  

Thanks, 

Jenna Triolo

**Comment by ironikart** [comment]
My suspicion is that the copy/paste function on the code sniffer webpage doesn't load your JavaScripts and execute them the same as it does on your live web page. The bookmarklet works by running on the DOM which may have been modified by JavaScript. I would lean towards using the bookmarklet for compliance right now. I will have to get some more information from the person that build that copy/paste utility on the code sniffer web page to be 100% certain so I'll leave this open until I have that answer.

**Comment by ironikart** [comment]
Hi Jenna, confirmed that the web browser copy/paste version on the site does not run your JavaScript, it's just there as an example for HTML validation only.

**Comment by selfthinker** [comment]
Just to clarify, just because HTML_CodeSniffer doesn't return any errors, that doesn't mean that your page is compliant. That's true for any accessibility testing tool. They can only ever find a small subset of issues. Please don't confuse passing tests from these tools with being compliant.
