### ISSUE TITLE
Tests run is not succeeded

### ISSUE THREAD

**Issue by podarok** [squizlabs/HTML_CodeSniffer#183]
```
bash ./run_tests.sh 
ReferenceError: Can't find variable: HTMLCS_RUNNER
```

```
HTML_CodeSniffer-master/Contrib/PhantomJS$ phantomjs HTMLCS_Run.js http://example.com WCAG2A
ReferenceError: Can't find variable: HTMLCS_RUNNER
```

```
phantomjs -v
2.1.1
```
same is on 1.9.x

Could you help to run these tests somehow?

**Comment by podarok** [comment]
sorry, I had to check Readme file.
After grunt build all works fine

**Comment by EugenMazanik** [comment]
Have the same problem. 
"ReferenceError: Can't find variable: HTMLCS_RUNNER"
in 
[page.evaluate(function(standard) {HTMLCS_RUNNER.run(standard);}, standard);](https://github.com/squizlabs/HTML_CodeSniffer/blob/aec6f3718afb3a4fa1c410567529276a1167ebfd/Contrib/PhantomJS/HTMLCS_Run.js#L170)



Grunt does not need.
> If you are using command-line processing, you don't need to build the auditor as above.
