### ISSUE TITLE
Incorrect reporting of error: This label's "for" attribute contains an ID that does not exist in the document.

### ISSUE THREAD

**Issue by iandevlin** [squizlabs/HTML_CodeSniffer#187]
Hi,

First of all many thanks for this tool, it's very useful indeed and the work put into it is greatly appreciated.

I came across bug #22 but I'm finding the same thing happening again on the live site (v2.0.7) when I paste a code snippet for evaluation. The snippet in question only has a `label` but actually has no `for` attribute (Google Maps code...). The bookmarked version of the CodeSniffer doesn't report this issue at all.

**Comment by ironikart** [comment]
Hi, Are you able to paste some example code that is failing so we can test it? The code used in #22 seems to be working ok in the copy/paste scenario from the hosted tool. You may also want to test this with the bookmarklet rather than the copy/paste tool, although both should work.

**Comment by iandevlin** [comment]
Hi, thanks for the reply. I will post the code when I am back in the office, and yes the bookmarklet doesn't report it.

**Comment by iandevlin** [comment]
A simple code snippet of `<label>Text</label>` causes the issue to appear. I think it's a case of the error message being misleading, as the `label` has no `for` attribute, but it should. Perhaps the error message in this case could be changed to reflect that?
Thanks for your time!

**Comment by ironikart** [comment]
I see what you mean, the error is misleading. I will look into this for the next release.

**Comment by iandevlin** [comment]
Thanks a lot, much appreciated! And thanks again for all your work on this.
