### ISSUE TITLE
Alt Tag vs Aria-Label vs Aria-labeledby

### ISSUE THREAD

**Issue by onefatguy** [squizlabs/HTML_CodeSniffer#189]
Hi guys,

Been reading everyone comments on Alt and Aria labels and I am it may have been answered already, if so, sorry.

We have a blog page here at work and we have to be 508 government compliant and our blog page can contain either:
1. Static Image
2. Infographic
3. Video

This is where I get a little confused about which to use and why? Traditional you use ALT tag"" for describing an image for web crawlers and SEO. You could also use the ALT tag"" for a description of an Image, Infographic, and or video. So, my question is this, how does one use both tags at the same time so that we can use ALT tag"" for keyword description for SEO and the ARIA-Label or ARIA-labeledby for the description of the Image, Infographic and or Video without repeating the ALT tag and aria label if they both contained the same information? Is there a way to code that a screen reader can skip ALT tag and just read ARIA labels so we don't repeat semantics.

Thanks so much for the info and help!!!

Taylor out!

**Comment by ironikart** [comment]
Hi Taylor,

In my experience a screen reader will prefer aria attributes and depending on which one you use it shouldn't matter if you have an alt tag with different content. In the past I've used aria attributes to associate captions (something like this: https://www.w3.org/WAI/GL/wiki/Using_aria-describedby_to_provide_descriptions_of_images).
