### ISSUE TITLE
HTML5 input types other than text fail success criteria: "4.1.2: Name, Role, Value"

### ISSUE THREAD

**Issue by ironikart** [squizlabs/HTML_CodeSniffer#196]
The code for 4_1_2 only validates against input[type="text"] and incorrectly validates input[type="email"] etc. as it doesn't match the known list of required names.

**Comment by oddjones** [comment]
wasted a whole morning trying to figure out why on earth my <input type="email"> was failing every time :-(

**Comment by Lucas-C** [comment]
Same for `<input type="search">`
They do not appear in the doc: https://squizlabs.github.io/HTML_CodeSniffer/Standards/WCAG2/4_1_2

**Comment by VolleMelk** [comment]
So who's at fault here? HTML CodeSniffer or the spec for lagging behind WCAG specs?

And: How to proceed? I'm using HTML CodeSniffer in CI and my builds are failing because of this
