### ISSUE TITLE
Auditor dialog can be dragged out of top of page

### ISSUE THREAD

**Issue by stefanruijsenaars** [squizlabs/HTML_CodeSniffer#197]
<img width="458" alt="screen shot 2017-07-03 at 13 18 27" src="https://user-images.githubusercontent.com/4950254/27790748-2814bb5e-5ff2-11e7-94be-373d96b28db6.png">

When dragging the dialog out of the top of the page, there is no way to move it/close it anymore, since the title bar is now unreachable

Possible solutions:
- disallow dragging it further than the top
- allow dragging it by clicking the whole window, or the edges

**Comment by djdany01** [comment]
I can take this 😄

**Comment by ironikart** [comment]
Fixed with #9a4c7fbedde8920144bb59045fb621f9f35cdb82
