### ISSUE TITLE
CodeSniffer does not open up and run  for https://www.tdbank.com/

### ISSUE THREAD

**Issue by sagar441989** [squizlabs/HTML_CodeSniffer#199]
I am using bookmarklet and trying to tun it against webpage https://www.tdbank.com/. The bookmarklet is not launching. It works fine for others.

**Comment by ironikart** [comment]
I've had a brief look at this and haven't been isolate what's happening exactly but my suspicion something to do with blocking cross-site javascript. There are many runtime and parse block warnings (viewed via chrome dev tools) which may be related. I'd suggest starting there. Perhaps copy the page and run it from a local web server and test it that way.

**Comment by sagar441989** [comment]
Thank you. I will try that way.
