### ISSUE TITLE
aria-label and no link content has been supplied

### ISSUE THREAD

**Issue by jssCUNY** [squizlabs/HTML_CodeSniffer#200]
Reported error: "Anchor element found with a valid href attribute, but no link content has been supplied."

FOR CODE
a class="cd-search-trigger" href="https://www.*.edu/@@search" aria-label="search"><span></span</a

Does not the aria-label provide the accessible name of the Search Icon link?

**Comment by ironikart** [comment]
This was fixed recently but not released in the bookmarklet yet. Reference issue #160. I'm looking at updating the bookmarklet today with a couple of recent fixes.
