### ISSUE TITLE
Possible Incorrect Reporting of: Duplicate id attribute value "" found on the web page.

### ISSUE THREAD

**Issue by mAAdhaTTah** [squizlabs/HTML_CodeSniffer#201]
It appears we have some 3rd-party scripts that are injected additional scripts with an empty id attribute. They look like this in the devtools:

![duplicate-id](https://user-images.githubusercontent.com/4371429/31019896-44e75384-a4ff-11e7-8479-8c868ffc4303.png)

HTML_CodeSniffer is reporting this as a duplicate id error.

**Comment by mAAdhaTTah** [comment]
@ironikart Thanks for the fix. After some additional discussion, we're wondering if the `id` attribute of `script` tags should be checked at all, since they're not relevant for accessibility. Thoughts?

**Comment by ironikart** [comment]
@mAAdhaTTah I think that even though most assistive technologies would ignore script tags the DOM spec still says it has to be unique in the document.

A use case may be JS apps that use script tags to store template data and referenced by id. The script tag lets the template content be hidden from assistive technologies, but the JS app turns the content into mounted DOM elements. A duplicate id here may indirectly cause accessibility issues.

It's a stretch, but the check is working now and we're just talking semantics not broken validation.

**Comment by mAAdhaTTah** [comment]
Fair. The fix was merged so I'll close this. Thanks for your help!
