### ISSUE TITLE
Incorrect errors for table headers if table cell contains another table

### ISSUE THREAD

**Issue by genafox** [squizlabs/HTML_CodeSniffer#204]
**Markup:**
<table>
	<tr>
		<th id="h">Row Id</th>
		<th id="e">Row Name</th>
		<th id="p">Row Files</th>
	</tr>
	<tr>
		<td headers="h">1</td>
		<td headers="e">Row 1</td>
		<td headers="p">
			<div style="margin: 5px">
				<table>
					<tr>
						<th id="X">File Id</th>
						<th id="Y">File Name</th>
						<th id="Z">File Extension</th>
					</tr>
					<tr>
						<td headers="X">1</td>
						<td headers="Y">File 1</td>
						<td headers="Z">DOCX</td>
					</tr>
					<tr>
						<td headers="X">2</td>
						<td headers="Y">File 2</td>
						<td headers="Z">PDF</td>
					</tr>
				</table>
			</div>
		</td>
	</tr>
</table>

**Actual Result:**
![nested_datatables_issue](https://user-images.githubusercontent.com/14916451/33931669-571a0d50-dff9-11e7-8ce1-fe1fcbf48465.png)

**Expected Result:**
These are two different tables with no relations. So that the headers for cells are specified correctly and no errors should be found

**Comment by alex-1244** [comment]
Is this fix released already?

**Comment by ironikart** [comment]
> Is this fix released already?

It's not released in the bookmarklet build yet, still in master branch awaiting release.
