### ISSUE TITLE
ReferenceError: _global is not defined

### ISSUE THREAD

**Issue by EvgenyOrekhov** [squizlabs/HTML_CodeSniffer#208]
The following Node.js example does not work: https://npm.runkit.com/html_codesniffer

**Comment by EvgenyOrekhov** [comment]
I can see now in the README that HTML_CodeSniffer is supposed to be used with JSDom and is not supposed to be required using `require("html_codesniffer")`.

That is confusing.

I would like the npm package to have a Node.js API, something like:

```js
const HTMLCS = require("html_codesniffer");
HTMLCS.run({html: '<img src="test.png" />'}, function (err, result) {...});
```

**Comment by ironikart** [comment]
I'll look into it for the next release. At this stage NPM is being used as an alternative way to fetch updates to the code for some organisations (#171).
