### ISSUE TITLE
Error for input with a type of "range"

### ISSUE THREAD

**Issue by rowanmanning** [squizlabs/HTML_CodeSniffer#210]
Currently I get an error for inputs with a type of `range` which seems unfixable. I might be missing something obvious but the following:

```html
<label for="example-range">Example</label>
<input id="example-range" name="range" type="range" min="0" max="100" step="1" value="100"/>
```

errors with:

> This range input element does not have a name available to an accessibility API. Valid names are: element content

But if I switch to a `text` input with near-identical markup, I get no error:

```html
<label for="example-text">Example</label>
<input id="example-text" name="text" type="text" value="100"/>
```

**Comment by leptest** [comment]
Looks like the color element might need to be added too?
