### ISSUE TITLE
HTML Report as an output of HTML code sniffer log

### ISSUE THREAD

**Issue by rakeshkmr516** [squizlabs/HTML_CodeSniffer#216]
HI Team

Awesome tool sniffs and reports violation based on rulesets 
Is there any possibility to show Report in HTML/any format which makes users easily identify issues 
Format: Standard |  Level  | Principle | Message | Element

**Comment by rakeshkmr516** [comment]
True. Am able to generate JSON 
However, if we are able to provide HTML based report in the below format it helps all users and kind of enhancement 
Format: Standard | Level | Principle | Message | Element
Json i have generated in the below format:
 {"Accessibility Violations":[{"AccessibilityType":"NOTICE","Description":"Check that text of the link describes the purpose of the link.","Tagname":"a","Element":"\\u003Ca href=\\\"\/Consortium\/sponsor\/\\\">...\\u003C\/a>\"","Standard":"WCAG2AAA.Principle2.Guideline2_4.2_4_9.H30"}]}

**Comment by ironikart** [comment]
Hi @rakeshkmr516 

The point I was trying to make is that a format like JSON makes it trivial to turn into HTML. It's unlikely we will add HTML export support directly in the core of the product.

Here is an example of using the existing PhantomJS script to turn JSON into HTML using node js:

`phantomjs HTMLCS_Run.js http://www.google.com WCAG2A json | node ./test.js`

test.js
```javascript
let data = '';

process.stdin.resume();
process.stdin.setEncoding('utf8');

process.stdin.on('data', function(chunk) {
    data += chunk;
});

function toHTML(obj) {
    return `<tr>
        <td>${obj.code}</td>
        <td>${obj.msg}</td>
    </tr>`;
}

process.stdin.on('end', function() {
    let issues = JSON.parse(data);
    let html = `<table>
        <thead>
            <tr>
                <th>Code</th>
                <th>Message<th>
            </tr>
        </thead>
        <tbody>
            ${issues.map(toHTML).join('')}
        </tbody>
    </table>`;
    console.log(html);
});
```

**Comment by rakeshkmr516** [comment]
Thank you for your response. Will try the same
