### ISSUE TITLE
HTML code sniffer throws TypeError: window.HTMLCS_RUNNER is undefined on Firefox browser

### ISSUE THREAD

**Issue by rakeshkmr516** [squizlabs/HTML_CodeSniffer#219]
Hi Team / @ironikart ,

I am calling JavaScript source directly in my script with the below format throwing TypeError: window.HTMLCS_RUNNER is undefined

`String jquery_content = Jsoup.connect("http://squizlabs.github.io/HTML_CodeSniffer/build/HTMLCS.js").ignoreContentType(true).execute().body();
			js.executeScript(jquery_content);
				js.executeScript("window.HTMLCS_RUNNER.run('WCAG2A');");	`

However, the same code is working on chrome browser and able to get accessibility violations
is there any limitation on Firefox browser and workarounds to get violations on Firefox

**Comment by ironikart** [comment]
@rakeshkmr516 There are no limitations for Firefox, it works in all modern browsers. I don't recognise the code you are using but it seems you are trying to use the PhantomJS runner in the wrong context, and without actually including the code (Contrib folder). If you are trying to use this server side you might want to check out the readme.
