### ISSUE TITLE
HTML_Codesniffer evaluating itself

### ISSUE THREAD

**Issue by simonol1** [squizlabs/HTML_CodeSniffer#230]
HTML_Codesniffer seems to be evaluating itself and reporting errors:

![screen shot 2018-09-10 at 3 30 01 pm](https://user-images.githubusercontent.com/24973297/45327245-1c593700-b59a-11e8-956f-c710d7d91d99.png)

a) iframe element requires a non-empty title attribute that identifies the frame.
b) A title should be provided for the document, using a non-empty title element in the head section.
c) The HTML element should have a lang or xml:lang attribute which describes the language of the document.

The page certainly has a title and a lang attribute. I'm not certain about the iframe, but I can't find it when doing a search. 

Using Google Chrome with the latest version of HTML_Codesniffer

**Comment by ironikart** [comment]
Hi @simonol1 

HTMLCS doesn't use those elements in it's own markup (it injects elements into the existing page DOM rather than embedding in an iframe) and I don't get any errors in a valid empty HTML document using Chrome with the latest bookmarklet. Can you link the page you are trying to validate?

**Comment by simonol1** [comment]
Thanks Anthony

This is the site that I'm trying to validate: https://www.ergon.com.au/

There must be an iframe on the page that I haven't spotted.

**Comment by ironikart** [comment]
It looks like there are iframes being added by some of the javascript libraries at runtime. If you have an addon that blocks them it might be why you don't see it, I had to disable mine. You could try incognito mode which usually disables any addons.

**Comment by simonol1** [comment]
I've found it now - thanks Anthony
