### ISSUE TITLE
Option to dismiss warnings

### ISSUE THREAD

**Issue by simonol1** [squizlabs/HTML_CodeSniffer#231]
Is there a feature on the roadmap to acknowledge/dismiss CSS warnings in Matrix? 

One in particular is tricky to fix:
![screen shot 2018-09-11 at 8 16 25 am](https://user-images.githubusercontent.com/24973297/45327490-0b5cf580-b59b-11e8-9788-5e3ce28ecc42.png)

**Comment by gsherwood** [comment]
HTMLCS doesn't have the ability to record that warnings are being ignored as it has no place to store this information. If you want your CMS to integrate with HTMLCS and implement a feature like this, you'd need to post a feature request over there.

**Comment by simonol1** [comment]
Thanks for your prompt response Greg
