### ISSUE TITLE
License not specified in package.json

### ISSUE THREAD

**Issue by paazmaya** [squizlabs/HTML_CodeSniffer#239]
Would it be possible to change the license to something broadly used, such as the MIT license?
https://spdx.org/licenses/MIT.html

Currently this project uses a license which is very similar but has the company called Squiz Pty Ltd involved.

The reason was asking this is to make it easier to use and contribute, since many possible users will demand such recognised license.

**Comment by gsherwood** [comment]
The licence is the BSD 3-clause, which allows you to do anything you want with the code, in any context.

The mention of Squiz is for copyright, which would be exactly the same if MIT was used.

Changing the licence should have no impact on the ease of contributions. What in particular is causing you a problem?

**Comment by paazmaya** [comment]
Automated license evaluation tools, such as Blackduck, will raise a flag on this when the license is not clear.

Even BSD 3-clause is fine, but currently it cannot be seen as such, since `license` property in `package.json` does not have nor the license file state it.

**Comment by gsherwood** [comment]
> since `license` property in `package.json` does not have nor the license file state it.

Then that looks to be the core problem here. Happy for me to change the title to reflect this?
