### ISSUE TITLE
New release to get recent changes published

### ISSUE THREAD

**Issue by paazmaya** [squizlabs/HTML_CodeSniffer#251]
Perhaps there needs to be a major version change, due to the Node.js version specification and since the published package now includes the build artifacts....

In any case, your call.

**Comment by ironikart** [comment]
The next release was something I was hoping to also get WCAG 2.1 support into but it's not looking likely at this stage. Will probably publish with the current changes on master branch.

**Comment by ironikart** [comment]
Changes have been published with 2.3.0. Any issues let us know.
