### ISSUE TITLE
Wrong contributor on changelog

### ISSUE THREAD

**Issue by jamadam** [squizlabs/HTML_CodeSniffer#269]
Thanks for crediting me on changelog. However, some of them were not me. Maybe @paazmaya?

- Travis CI config added by @jamadam
- Npm test refinement by @jamadam

https://github.com/squizlabs/HTML_CodeSniffer/blob/gh-pages/CHANGELOG.markdown
> Version 2.4.0 (21 May 2019)

**Comment by ironikart** [comment]
Thanks for picking that up, I'll look into it.

**Comment by ironikart** [comment]
Updated docs with 22d7b9f
