### ISSUE TITLE
Release 2.4.1 to NPM

### ISSUE THREAD

**Issue by apdrsn** [squizlabs/HTML_CodeSniffer#276]
Hi and thanks for the great work :)

Do you know when the updated WCAG2.1 standards will be released to NPM?
Currently working on a tool using Pa11y and would like to check for the new stuff from 2.1.

**Comment by gsherwood** [comment]
Can't give an exact ETA, but I'm actively working on scheduling a release. I'm hoping one will be out within the next 2 weeks.

**Comment by apdrsn** [comment]
@gsherwood Thanks for the reply. That would be awesome!

**Comment by Graatz** [comment]
Hello guys. Is there any new information about the release date of the WCAG 2.1 standard rulesets to npm? Thanks in advance.

**Comment by gsherwood** [comment]
I'm working on updating the docs in preparation for a release, which also lets me do a final review of messaging. It was probably within a week of release before everything shut down, but it all changed overnight and we've all had to adjust to a different way of working.

I have set some time aside next week to try and get this over the line though, so I'm going to tentatively say that a release is scheduled for next week.

**Comment by Graatz** [comment]
@gsherwood Thank you for the reponse! Good to hear the new version is soon to be released. Appreciate the great work :)

**Comment by gsherwood** [comment]
Version 2.5.0 has now been released: https://www.npmjs.com/package/html_codesniffer
