### ISSUE TITLE
Why not make this open source

### ISSUE THREAD

**Issue by mgifford** [squizlabs/HTML_CodeSniffer#295]
Why not just make this an open source tool like axe? It is presently being treated like that, but not under the MIT or GPL which is the default.

**Comment by gsherwood** [comment]
It is, and always has been, an open source project. It's released under the BSD 3-clause licence: https://github.com/squizlabs/HTML_CodeSniffer/blob/master/licence.txt

**Comment by mgifford** [comment]
Thanks. How did I miss that?  I think I expected to see a LICENSE.txt file in https://github.com/squizlabs/HTML_CodeSniffer
