### ISSUE TITLE
http://squizlabs.github.com/HTML_CodeSniffer/ will not work

### ISSUE THREAD

**Issue by PuneetGopinath** [squizlabs/HTML_CodeSniffer#297]
In the repo's url (provided at github right side details), you have provided http://squizlabs.github.com/HTML_CodeSniffer/
Please update it to http://squizlabs.github.io/HTML_CodeSniffer/
See [GitHub Pages will stop redirecting Pages sites from *.github.com after April 15, 2021](https://github.blog/changelog/2021-01-29-github-pages-will-stop-redirecting-pages-sites-from-github-com-after-april-15-2021/)

**Comment by gsherwood** [comment]
Thanks for pointing that out. I've updated the URL in the project info.

**Comment by PuneetGopinath** [comment]
Welcome
