### ISSUE TITLE
Chrome extension language stuck in Japanese

### ISSUE THREAD

**Issue by MiriamS** [squizlabs/HTML_CodeSniffer#298]
I downloaded the HTML_CodeSniffer Chrome extension from the Chrome Web Store. I thought the extension language would match the page it was used on or default to English. The one I got  was stuck in Japanese even when I looked at pages in various other languages. Then I added HTML_CodeSniffer to a different computer and the same thing happened. I live in California, so the geolocation isn't the issue. Since I don't know Japanese, it would be great to have a fix.

**Comment by gsherwood** [comment]
This extension was not built by this project. I wasn't even aware it existed until you pointed it out :)

I'm not sure how to provide the project feedback, but you'll need to get in touch with them directly.

Sorry I can't be of more help.
