### ISSUE TITLE
1.4.3 Colour contrast problems with background images

### ISSUE THREAD

**Issue by elementalfire23** [squizlabs/HTML_CodeSniffer#54]
I have warnings for elements that are no longer set on background images! 

I've been converting all our gradient images into css gradients and the sniffer is still throwing a warning for them.

**Comment by ironikart** [comment]
Positioned elements were somewhat accounted for previously, but I have added code that should resolve a bug with it in b2ef21bc9b2544380ce41d970a6e1e18e5c313a9. Closing this issue off.
