### ISSUE TITLE
Reporting of html code sniffer

### ISSUE THREAD

**Issue by booma** [squizlabs/HTML_CodeSniffer#72]
I use the phantomjs version of html code sniffer, but i am looking for an kind of reporting in xml format so that i can use in continuous integration tool

**Comment by andrewholgate** [comment]
> Are there any particular standards of XML (Checkstyle comes to mind) that would be helpful for this cause? @lwright-sq

I would be prepared to work on a Checkstyle XML output if you could let me a hand with the appropriate format.

I am not very familiar with the Checkstyle formatting but as far as I can tell, you need to include a `<file>` element? In this case, we could use the URL being tested but I am not sure if this would be the correct approach. Something like this?

```XML
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle>
  <file name="http://www.example.com">
    <error message="Img element is the only content of the link, but is missing alt text. The alt text should describe the purpose of the link." severity="error" source="1_1_1.H30.2"/>
    <error message="If this selection list contains groups of related options, they should be grouped with optgroup." severity="warning" source="1_3_1.H85.2"/>
    <error message="Check that the link text combined with programmatically determined link context identifies the purpose of the link." severity="info" source="2_4_4.H77,H78,H79,H80,H81"/>
  </file>
</checkstyle>
```

**Comment by ironikart** [comment]
Resolved by adding JSON as the optional machine readable format produced by the phantomjs runner. JSON is a more natural fit and the work had already been completed and sent as a pull request some time ago.

Usage as follows:
```bash
phantomjs Contrib/PhantomJS/HTMLCS_Run.js <url> json
```

**Comment by andrewholgate** [comment]
@ironikart great, thanks!

**Comment by vinitaprasad** [comment]
Hello,  As of now I can simply see or copy paste the errors or warnings shown. Is there any way I can pull report from HTML_CodeSniffer.

**Comment by ironikart** [comment]
@vinitaprasad You can use the command line to output a file in different formats.

Use the following where the <format> is either 'default' (will use this if you omit the argument), 'table' (a formatted text table), or 'json' if you need to make it a machine readable format.
```
phantomjs Contrib/PhantomJS/HTMLCS_Run.js <url> <format>
```

**Comment by vinitaprasad** [comment]
Thank you @ironikart . Tried this but I am getting error 
'phantomjs' is not recognized as an internal or external command,
operable program or batch file.

Is there any pre-requisite that I can do in order to pull report successfully.

**Comment by ironikart** [comment]
HI @vinitaprasad, apologies, there is some assumed knowledge with the command I gave you to run. You will need to install PhantomJS and have it accessible to the command line and it sounds like you are using windows so I'm not familiar with the setup for that. We don't have instructions on how to set up all the pre-requisites but the [PhantomJS](http://phantomjs.org/quick-start.html) site might be a good place to start.
