### ISSUE TITLE
support a commonjs-enabled environment

### ISSUE THREAD

**Issue by stephenmathieson** [squizlabs/HTML_CodeSniffer#73]
it'd be quite useful to include codesniffer in a few of my applications for testing purposes.  unless there are any objections, i'd like to get around to adding support for a commonjs-style `require` of codesniffer.  thoughts?

**Comment by ironikart** [comment]
Adding a cross reference to #166 and #171.

**Comment by ironikart** [comment]
Resolved with f79cf0a2584f0a69760e0d5518bab77593084275. It should be noted that HTML_CodeSniffer still requires a browser environment which means that requiring it directly in Node will still result in an error.
