### ISSUE TITLE
How do you build?

### ISSUE THREAD

**Issue by pmcelhaney** [squizlabs/HTML_CodeSniffer#81]
It looks like you're just concatenating and minifying all the files. Do they have the be in any particular order? Is there a command or build script I can run?

**Comment by lwright-sq** [comment]
I'm going to close this, because essentially the way it's built at the moment is still the same as above, and the official build (for the auditor etc) is done essentially the same way now. Still works correctly for me with the newest Node (6.0) that came out this week.

**Comment by lwright-sq** [comment]
I will just finalise this with:
- As of today, I've moved the gruntfile to the top directory, so you no longer have to go to Contrib/Grunt for that: just run "grunt build" from the top.
- I'm going to put brief documentation into the README.markdown as to how to do this.

Thanks again~
