### ISSUE TITLE
Heading detected as empty when it's actually hN > a > img[alt="something"]

### ISSUE THREAD

**Issue by PhilippeVay** [squizlabs/HTML_CodeSniffer#85]
The following code:

        <h1>
          <a href="http://www.alsacreations.com/" accesskey="1"
                      title="Alsacréations, apprentissage des standards web, accueil">
            <img id="logo" alt="Accueil - Alsacreations.com" src="image.png"
                      height="80" width="290">
          </a>
        </h1>

found in http://www.alsacreations.com (main logo in upper left part of the page) is detected as: "*Heading tag found with no content. Text that is not intended as a heading should not be marked up with heading tags*" but the content is "*Accueil - Alsacreations.com*" as an image in a link.

Relevant code in HTML_CodeSniffer seems to be the function `testEmptyHeading` in 1_3_1.js but I'm not sure how it could be improved (I'm just discovering the code behind your tool and I'm more a CSS/accessibility guy than a developer...).  
Is there a class/function somewhere that could return content from child element, including text alternative for images: maybe something similar to `testNullAltText` in 1_1_1, if no other content was found prior to that and there are images in a heading?

**Comment by cptvitamin** [comment]
+1
