### ISSUE TITLE
Anchor links to name="" throwing errors

### ISSUE THREAD

**Issue by justincavery** [squizlabs/HTML_CodeSniffer#86]
When a link is to an anchor it will throw an error if that anchor isn't declared as an id.  This should pass if the anchor is declared within the name attribute also.

The code below is valid but is throwing an Error because top isn't declared as an id.
```css
<h1 name="top">Heading</h1>
<a href="#top">back to top</a>
```

**Comment by lwright-sq** [comment]
I'm coming back to this one and marking this as a HTML5 issue. In HTML5 "name" on a header is not permitted, but is not a problem in HTML 4, so this would need a document type switch to properly fix.
