### ISSUE TITLE
1.4.3 on Disabled Input Elements

### ISSUE THREAD

**Issue by kabel** [squizlabs/HTML_CodeSniffer#93]
There has been some debate regarding if disabled (by means of the disabled attribute or ARIA) elements are exempt from contrast requirements. 

It is my understanding that these elements _are_ considered "inactive user interface component" (as defined by the spec), and should be skipped during the contrast test.

**Comment by lwright-sq** [comment]
Hi,

Sorry for the very slow response to this issue. I was recalled to it by an internal request for something similar.

There's been work done on it (as seen in the issue history above) and it's now in Auditor version 2.0.4, released last Monday (2015-02-02). It should trigger based on the "disabled" IDL attribute [which should include HTML5 "disabled" attributes among other things] and the aria-disabled="true" attribute.

Hope this helps, and thanks for the report!
